Offline signing
harmony-one/go-sdk pull request #258
Opened 2021-06-06 15:35 UTC by LuttyYang

https://github.com/harmony-one/go-sdk/issues/251

2021-06-13 19:20 UTC, hayalet27 requested changes
Calismayan sorunu incelemisin

2021-06-13 19:23 UTC, hayalet27 approved these changes
Onay için inceleme gerekiyor

2021-06-15 06:35 UTC, LuttyYang commented
@hayalet27 Can you provide more information about not working?

2021-07-08 20:47 UTC, hayalet27 approved these changes

2021-07-09 08:12 UTC, LeoHChen approved these changes

2021-07-09 08:12 UTC, merged